/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();
        Identitas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 110, 14);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 70, 14);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(160, 80, 180, 20);

        Identitas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Identitas.setToolTipText("Identitas");
        Identitas.setAutoscrolls(true);
        Identitas.setName("identitas"); // NOI18N
        Identitas.setVerifyInputWhenFocusTarget(false);
        Identitas.setLayout(null);

        jLabel4.setText("Dokter Spesialis");
        Identitas.add(jLabel4);
        jLabel4.setBounds(20, 350, 110, 20);

        jLabel5.setText("Nama");
        Identitas.add(jLabel5);
        jLabel5.setBounds(20, 30, 50, 20);

        jLabel6.setText("Alamat");
        Identitas.add(jLabel6);
        jLabel6.setBounds(20, 70, 50, 20);

        jLabel7.setText("Usia");
        Identitas.add(jLabel7);
        jLabel7.setBounds(20, 110, 50, 20);

        jLabel8.setText("Jenis Kelamin");
        Identitas.add(jLabel8);
        jLabel8.setBounds(20, 150, 100, 20);

        jLabel9.setText("Golongan Darah");
        Identitas.add(jLabel9);
        jLabel9.setBounds(20, 190, 100, 20);

        jLabel10.setText("Status");
        Identitas.add(jLabel10);
        jLabel10.setBounds(20, 230, 70, 20);

        jLabel11.setText("Kewarganegaraan");
        Identitas.add(jLabel11);
        jLabel11.setBounds(20, 270, 110, 20);

        jLabel12.setText("Waktu Praktek");
        Identitas.add(jLabel12);
        jLabel12.setBounds(20, 310, 90, 20);
        Identitas.add(jtxtnama);
        jtxtnama.setBounds(130, 30, 140, 30);
        Identitas.add(jtxtwaktu);
        jtxtwaktu.setBounds(130, 350, 140, 30);
        Identitas.add(jtxtalamat);
        jtxtalamat.setBounds(130, 70, 140, 30);
        Identitas.add(jtxtusia);
        jtxtusia.setBounds(130, 110, 140, 30);
        Identitas.add(jtxtjenis);
        jtxtjenis.setBounds(130, 150, 140, 30);
        Identitas.add(jtxtgol);
        jtxtgol.setBounds(130, 190, 140, 30);
        Identitas.add(jtxtstatus);
        jtxtstatus.setBounds(130, 230, 140, 30);
        Identitas.add(jtxtkewar);
        jtxtkewar.setBounds(130, 270, 140, 30);
        Identitas.add(jtxtspesial);
        jtxtspesial.setBounds(130, 310, 140, 30);

        getContentPane().add(Identitas);
        Identitas.setBounds(40, 130, 300, 380);
        Identitas.getAccessibleContext().setAccessibleName("identitas");

        setBounds(0, 0, 417, 569);
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
        if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){             
            jtxtnama.setText("DR. Farras Yassar ");             
            jtxtalamat.setText("Jl. Surabaya 16, Malang");             
            jtxtusia.setText("20 Tahun");             
            jtxtjenis.setText("Laki-Laki");             
            jtxtgol.setText("A");             
            jtxtstatus.setText("Belum Menikah ");             
            jtxtkewar.setText("Indonesia");             
            jtxtspesial.setText("Dokter Umum");             
            jtxtwaktu.setText(" Pagi (07.00-15.00)");         
        }         
        else if(jconadokt.getSelectedItem().equals("DR. Anisa Putri ")){             
                jtxtnama.setText("DR. Anisa Putri");             
                jtxtalamat.setText("Jl. Veteran 3, Malang");             
                jtxtusia.setText("20 Tahun");             
                jtxtjenis.setText("Perempuan");            
                jtxtgol.setText("O");             
                jtxtstatus.setText("Belum Menikah"); 
                jtxtkewar.setText("Indonesia");             
                jtxtspesial.setText("Dokter Gigi");             
                jtxtwaktu.setText(" Sore (16.00-22.00)");         
            }         
        else if(jconadokt.getSelectedItem().equals("DR. Harun Fajar ")){             
                    jtxtnama.setText("DR. Harun Fajar ");             
                    jtxtalamat.setText("Jl. Bandung 9, Malang");             
                    jtxtusia.setText("20 Tahun");             
                    jtxtjenis.setText("Laki-Laki");             
                    jtxtgol.setText("B");             
                    jtxtstatus.setText("Belum Menikah");             
                    jtxtkewar.setText("Indonesia");             
                    jtxtspesial.setText("Dokter Gizi");             
                    jtxtwaktu.setText(" Malam (22.00-06.00)");         
                }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Identitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
